### ISSUE TITLE
cloudflare access 우회 가능

### ISSUE THREAD

**Issue by andromedarabbit** [unchartedsky/greenday#5]
`https://unchartedsky.com/wp-login.php` 로 직접 주소를 치고 들어가면 액세스를 우회할 수 있습니다.

어떤 경우에는 액세스로 넘어가고 어떤 경우는 안 넘어가는데 정확한 규칙을 찾는 중입니다.

**Comment by gendalf9** [comment]
@andromedarabbit 이거 안그래도 막 설정 추가했습니다 ㅎ 여기는 유저 로그인할때만 타는 곳이려나 싶어서 일단 github 인증만 추가하긴 했는데요. 

그런데 캐싱을 타서 그런가...시크릿 탭으로 열지 않으면 그냥 통과되고...새로 연 브라우저에서는 wp-login으로 들어가도 깃헙으로 잘 이동하고 그러네요 ㅎ;

**Comment by andromedarabbit** [comment]
쿠키인 것 같네요. 실제 우회가 되는 것은 아닌 듯 하고 사소한 문제이니 티켓 닫아도 무방할 것 같습니다.
